-- This 3 tables  I used in this project
SELECT * FROM iloilo_flights;
SELECT * FROM iloilo_airlines;
SELECT * FROM iloilo_passengers;

-- problem Scenario1: Which airline has the most passengers?
	SELECT f.airline, COUNT(p.passenger_id) AS total_passenger
	FROM iloilo_flights f
	JOIN iloilo_passengers p 
		ON f.flight_id = p.flight_id
	GROUP BY f.airline
	ORDER BY total_passenger DESC;

-- problem Scenario 2: Which airline has the most passengers affected by delayed flights?
-- using CTE Query
	WITH Delayed_flight AS (
		SELECT f.flight_id, f.airline, f.status,origin,
			   f.passenger_count AS affected_passenger
		FROM iloilo_flights f
		WHERE f.status = 'Delayed'
		GROUP BY f.flight_id, f.airline, f.status
	)
	SELECT airline,origin,
		   SUM(affected_passenger) AS total_affected,
		   status AS their_status
	FROM Delayed_flight
	GROUP BY airline, status
	ORDER BY total_affected DESC;

-- ranking airlines based on their Average Ticket Price
	SELECT airline,
		   AVG(ticket_price) AS avg_ticket_price,
		   RANK() OVER (ORDER BY avg_ticket_price DESC) AS rank_of_airline
	FROM iloilo_flights
	GROUP BY airline
	ORDER BY rank_of_airline ASC;

-- find flights with above-average passenger counts
SELECT flight_id, airline, passenger_count
FROM iloilo_flights
WHERE passenger_count > (
    SELECT AVG(passenger_count) FROM iloilo_flights
)
ORDER BY passenger_count DESC;


-- how many flights affected by cloudy and rainy condition flights
SELECT f.airline, aircraft_type,
       COUNT( f.flight_id) AS total_bad_weather_flights
FROM iloilo_flights f
WHERE f.weather_condition = 'Rainy' & 'Coudy'
GROUP BY f.airline
ORDER BY total_bad_weather_flights DESC;

-- total income of all airline
WITH ticket_prices AS (
    SELECT airline, flight_id, SUM(ticket_price) AS total_income
    FROM iloilo_flights
    GROUP BY airline, flight_id
)
SELECT airline, SUM(total_income) AS total_income_per_airline
FROM ticket_prices
GROUP BY airline
ORDER BY total_income_per_airline DESC;

-- cumulative flight revenue analysis using Window functions
SELECT airline, flight_id,ticket_price,
SUM(ticket_price) OVER (PARTITION BY airline ORDER BY ticket_price ASC) AS rolling_prices
FROM iloilo_flights;

-- Which flights to Iloilo generate the highest income per airline, and how do they rank compared to other flights within the same airline?
SELECT 
	f.flight_id, airline, origin, destination,COUNT(*),	
    SUM(f.ticket_price) AS total_income,
    RANK() OVER (PARTITION BY airline ORDER BY SUM(f.ticket_price) DESC) AS rank_of_airline,
    DENSE_RANK() OVER (PARTITION BY airline ORDER BY SUM(f.ticket_price) DESC) AS dense_ranking,
    ROW_NUMBER() OVER (PARTITION BY airline ORDER BY SUM(f.ticket_price) DESC) AS row_numbering
FROM iloilo_flights f
JOIN iloilo_passengers p 
    ON f.flight_id = p.flight_id
WHERE destination = 'Iloilo'
GROUP BY airline, origin, destination
ORDER BY rank_of_airline, dense_ranking,row_numbering;

-- This SQL query analyzes the total and average income generated by airlines for flights originating from Hong Kong and Singapore. --
WITH total_income AS(
SELECT airline, origin AS Where_From, flight_id, SUM(ticket_price * passenger_count) As Total_Income
FROM iloilo_flights
GROUP BY airline, flight_id

), AVG_income AS(
	SELECT airline,Where_From,
    AVG(Total_Income) AS Avg_Income,
    SUM(Total_Income) AS All_Income
    FROM total_income
    GROUP BY airline,Where_From
	)
    SELECT * FROM AVG_income
    WHERE Where_From IN ('Singapore', 'Hong Kong')
    ORDER BY AVG_Income DESC, All_Income DESC;
    
SELECT airline, AVG(ticket_price) AS avg_pricing
FROM iloilo_flights 
GROUP BY airline
ORDER BY avg_pricing DESC;

SELECT airline,origin,ticket_price AS price,
SUM(ticket_price) OVER (Partition By airline Order by price asc) as ROLLING
FROM iloilo_flights
WHERE origin = 'Hong Kong'


